### ISSUE TITLE
NullPointerException is thrown for current day

### ISSUE THREAD

**Issue by dotemacs** [clojureverse/clojurians-log-app#93] opened 2020-04-03 12:11 UTC
Today is 3rd April, so I wanted to check something for today's archive, because I'd like to refer to it by a URL from this app, so I opened: 

https://clojurians-log.clojureverse.org/crux/2020-04-03

which gave me this error:

![image](https://user-images.githubusercontent.com/152363/78358993-af562980-75a3-11ea-861e-cc36b67d339e.png)

**Comment by oxalorg** [comment] 2020-11-05 11:25
I'm not able to reproduce this. Perhaps this has been fixed since the issue was created?

Tried the following links:
- https://clojurians-log.clojureverse.org/crux/2020-11-05
- https://clojurians-log.clojureverse.org/crux/2020-11-06
- https://clojurians-log.clojureverse.org/calva/2020-11-05

**Comment by plexus** [comment] 2020-11-05 13:52
I think we can close this, if it comes up again folks can open a new issue.

**Closed by plexus** 2020-11-05 13:52 UTC
